-- Generated from generator/demo_specs/aws-malaysia-oil-gas-exploration.json
-- Regenerate with: python3 generator/gen_repo_docs.py aws-malaysia-oil-gas-exploration
-- This is the schema that is actually deployed for MY_OIL_GAS_EXPLORATION.

-- Alerts fire on the bottom tail of Exploration Wells
-- (lower is worse for this metric).
CREATE OR REPLACE DYNAMIC TABLE CURATED.PERFORMANCE_SUMMARY
  TARGET_LAG = '30 days' WAREHOUSE = TOURISM_WH
  REFRESH_MODE = FULL INITIALIZE = ON_CREATE
AS
WITH thresh AS (
  SELECT PERCENTILE_CONT(0.09) WITHIN GROUP (ORDER BY KPI_EXPLORATION_WELLS) AS T
  FROM RAW.PRODUCTION_LOGS
)
SELECT
  e.ID AS ENTITY_ID,
  e.NAME AS ENTITY_NAME,
  e.REGION,
  e.CATEGORY,
  e.STATUS,
  COUNT(*) AS EVENT_COUNT,
  SUM(CASE WHEN f.KPI_EXPLORATION_WELLS <= (SELECT T FROM thresh) THEN 1 ELSE 0 END) AS ALERT_COUNT,
  ROUND(AVG(f.KPI_EXPLORATION_WELLS), 2) AS AVG_EXPLORATION_WELLS,
  ROUND(AVG(f.KPI_SUCCESS_RATE), 2) AS AVG_SUCCESS_RATE,
  ROUND(AVG(f.KPI_RESOURCES_ADDED), 2) AS AVG_RESOURCES_ADDED,
  ROUND(AVG(f.KPI_AI_PROSPECT_SCORE), 2) AS AVG_AI_PROSPECT_SCORE,
  ROUND(AVG(f.KPI_SEISMIC_COVERAGE), 2) AS AVG_SEISMIC_COVERAGE,
  ROUND(AVG(f.KPI_DRILLING_COST_WELL), 2) AS AVG_DRILLING_COST_WELL
FROM RAW.PRODUCTION_LOGS f
JOIN RAW.MALAYSIA_OG_MACRO e ON e.ID = f.ENTITY_ID
CROSS JOIN thresh
GROUP BY e.ID, e.NAME, e.REGION, e.CATEGORY, e.STATUS;

CREATE OR REPLACE DYNAMIC TABLE CURATED.TREND_ANALYSIS
  TARGET_LAG = '30 days' WAREHOUSE = TOURISM_WH
  REFRESH_MODE = FULL INITIALIZE = ON_CREATE
AS
SELECT
  f.EVENT_DATE AS METRIC_DATE,
  COUNT(*) AS EVENT_COUNT,
  ROUND(AVG(f.KPI_EXPLORATION_WELLS), 2) AS AVG_EXPLORATION_WELLS,
  ROUND(AVG(f.KPI_SUCCESS_RATE), 2) AS AVG_SUCCESS_RATE,
  ROUND(AVG(f.KPI_RESOURCES_ADDED), 2) AS AVG_RESOURCES_ADDED,
  ROUND(AVG(f.KPI_AI_PROSPECT_SCORE), 2) AS AVG_AI_PROSPECT_SCORE,
  ROUND(AVG(f.KPI_SEISMIC_COVERAGE), 2) AS AVG_SEISMIC_COVERAGE,
  ROUND(AVG(f.KPI_DRILLING_COST_WELL), 2) AS AVG_DRILLING_COST_WELL
FROM RAW.PRODUCTION_LOGS f
GROUP BY f.EVENT_DATE;

-- DISPLAY is rendered here so it is byte-identical to the card the app
-- was designed with (asserted by the round-trip check in kpi_parse.py).
CREATE OR REPLACE DYNAMIC TABLE CURATED.KPI_SUMMARY
  TARGET_LAG = '30 days' WAREHOUSE = TOURISM_WH
  REFRESH_MODE = FULL INITIALIZE = ON_CREATE
AS WITH ev AS (SELECT AVG(KPI_EXPLORATION_WELLS) AS KPI_EXPLORATION_WELLS, AVG(KPI_SUCCESS_RATE) AS KPI_SUCCESS_RATE, AVG(KPI_RESOURCES_ADDED) AS KPI_RESOURCES_ADDED, AVG(KPI_AI_PROSPECT_SCORE) AS KPI_AI_PROSPECT_SCORE, AVG(KPI_SEISMIC_COVERAGE) AS KPI_SEISMIC_COVERAGE, AVG(KPI_DRILLING_COST_WELL) AS KPI_DRILLING_COST_WELL FROM RAW.PRODUCTION_LOGS),
     en AS (SELECT SUM(KPI_SEISMIC_KM) AS KPI_SEISMIC_KM FROM RAW.MALAYSIA_OG_MACRO)
  SELECT 1 AS SORT_ORDER, 'Exploration Wells' AS TITLE, KPI_EXPLORATION_WELLS AS VALUE_NUM, TO_VARCHAR(CAST(ROUND((KPI_EXPLORATION_WELLS)) AS DECIMAL(38,0))) AS DISPLAY, 'neutral' AS STATUS FROM ev CROSS JOIN en
UNION ALL
  SELECT 2 AS SORT_ORDER, 'Success Rate' AS TITLE, KPI_SUCCESS_RATE AS VALUE_NUM, TO_VARCHAR(CAST(ROUND((KPI_SUCCESS_RATE)) AS DECIMAL(38,0))) || '%' AS DISPLAY, 'neutral' AS STATUS FROM ev CROSS JOIN en
UNION ALL
  SELECT 3 AS SORT_ORDER, 'Resources Added' AS TITLE, KPI_RESOURCES_ADDED AS VALUE_NUM, TO_VARCHAR(CAST(ROUND((KPI_RESOURCES_ADDED)) AS DECIMAL(38,0))) || ' ' || 'MMboe' AS DISPLAY, 'neutral' AS STATUS FROM ev CROSS JOIN en
UNION ALL
  SELECT 4 AS SORT_ORDER, 'Seismic (km²)' AS TITLE, KPI_SEISMIC_KM AS VALUE_NUM, LTRIM(TO_VARCHAR(CAST(ROUND((KPI_SEISMIC_KM)) AS DECIMAL(38,0)), '999,999,999,999')) AS DISPLAY, 'neutral' AS STATUS FROM ev CROSS JOIN en
UNION ALL
  SELECT 5 AS SORT_ORDER, 'AI Prospect Score' AS TITLE, KPI_AI_PROSPECT_SCORE AS VALUE_NUM, TO_VARCHAR(CAST(ROUND((KPI_AI_PROSPECT_SCORE)) AS DECIMAL(38,0))) || '%' AS DISPLAY, 'neutral' AS STATUS FROM ev CROSS JOIN en
UNION ALL
  SELECT 6 AS SORT_ORDER, 'Seismic Coverage' AS TITLE, KPI_SEISMIC_COVERAGE AS VALUE_NUM, TO_VARCHAR(CAST(ROUND((KPI_SEISMIC_COVERAGE)) AS DECIMAL(38,0))) || '%' AS DISPLAY, 'neutral' AS STATUS FROM ev CROSS JOIN en
UNION ALL
  SELECT 7 AS SORT_ORDER, 'Drilling Cost/Well' AS TITLE, KPI_DRILLING_COST_WELL AS VALUE_NUM, 'RM' || ' ' || TO_VARCHAR(CAST(ROUND(((KPI_DRILLING_COST_WELL) / 1000000)) AS DECIMAL(38,0))) || 'M' AS DISPLAY, 'neutral' AS STATUS FROM ev CROSS JOIN en;

ALTER DYNAMIC TABLE CURATED.PERFORMANCE_SUMMARY SUSPEND;
ALTER DYNAMIC TABLE CURATED.TREND_ANALYSIS SUSPEND;
ALTER DYNAMIC TABLE CURATED.KPI_SUMMARY SUSPEND;
