-- ============================================================================
-- 06_ML_MODELS.SQL — ML Functions for Upstream Exploration Analytics
-- ============================================================================
USE DATABASE OIL_GAS_EXPLORATION;
USE SCHEMA ML;

-- ML.FORECAST: PRODUCTION_DECLINE_MODEL
CREATE OR REPLACE SNOWFLAKE.ML.FORECAST ML.PRODUCTION_DECLINE_MODEL(
  INPUT_DATA => SYSTEM$REFERENCE('TABLE', 'CURATED.PRODUCTION_TIMESERIES'),
  SERIES_COLNAME => 'WELL_ID',
  TIMESTAMP_COLNAME => 'DS',
  TARGET_COLNAME => 'Y'
  
);

CREATE OR REPLACE TABLE ML.PRODUCTION_DECLINE_MODEL_RESULTS AS
SELECT * FROM TABLE(ML.PRODUCTION_DECLINE_MODEL!FORECAST(FORECASTING_PERIODS => 14));

