-- ============================================================================
-- 99_RESET.SQL — Reset Upstream Exploration Analytics to clean demo state
-- ============================================================================
USE DATABASE OIL_GAS_EXPLORATION;

-- Suspend tasks during demo
ALTER TASK IF EXISTS APP.TASK_RETRAIN_DECLINE_MODELS SUSPEND;
ALTER TASK IF EXISTS APP.TASK_REFRESH_AI SUSPEND;
ALTER TASK IF EXISTS APP.TASK_REFRESH_ICEBERG SUSPEND;

-- Force refresh Dynamic Tables
ALTER DYNAMIC TABLE CURATED.WELL_PERFORMANCE_SUMMARY REFRESH;
ALTER DYNAMIC TABLE CURATED.PRODUCTION_TIMESERIES REFRESH;
ALTER DYNAMIC TABLE CURATED.BLOCK_ECONOMICS REFRESH;
ALTER DYNAMIC TABLE CURATED.RESERVES_MOVEMENT REFRESH;

-- Verify key demo numbers
-- SELECT COUNT(*) FROM OIL_GAS_EXPLORATION.RAW.WELLS → 200
-- SELECT COUNT(*) FROM OIL_GAS_EXPLORATION.RAW.PRODUCTION_LOGS → 100000
-- SELECT COUNT(DISTINCT BLOCK_ID) FROM OIL_GAS_EXPLORATION.CURATED.BLOCK_ECONOMICS → 8

-- Resume tasks
ALTER TASK IF EXISTS APP.TASK_REFRESH_ICEBERG RESUME;
ALTER TASK IF EXISTS APP.TASK_REFRESH_AI RESUME;
ALTER TASK IF EXISTS APP.TASK_RETRAIN_DECLINE_MODELS RESUME;
